DROP TABLE IF EXISTS lead_gen;

CREATE TABLE lead_gen (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
company_name TEXT NOT NULL,
position TEXT NOT NULL,
job_link TEXT NOT NULL,
tech_used TEXT NOT NULL,
date_applied DATE NOT NULL,
phone_screen_date DATE,
behavior_interview DATE,
technical_interview DATE,
final_interview DATE,
job_offer VARCHAR (255),
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL);